# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='people',
        ),
    ]
