# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_people'),
    ]

    operations = [
        migrations.DeleteModel(
            name='people',
        ),
    ]
