# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_delete_people'),
        ('webapp', '0006_friend'),
    ]

    operations = [
    ]
