# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20171028_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='album',
        ),
        migrations.AddField(
            model_name='album',
            name='photo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Photos'),
        ),
    ]
