# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_album_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='author',
            new_name='a_author',
        ),
    ]
