# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20171028_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='a_name',
            new_name='album_name',
        ),
    ]
