# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 20:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0013_auto_20171028_1531'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together=set([('a_author', 'album_name')]),
        ),
    ]
