# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20171028_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Album')),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Photos')),
            ],
        ),
    ]
