# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Album'),
        ),
    ]
